import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Stories from "../components/Stories";
import Story from "../components/Story";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Instagram</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Stories />
      <Story
        avatar="/profile.png"
        caption="This is a post that I am writing for testing"
        comments={100}
        image="/trerry.png"
        likes={20}
        name="PhantomKnight"
        shares={45}
        timestamp="1 Hour Ago"
      />
    </div>
  );
};

export default Home;
