import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Stories from '../components/Stories'
import Story from '../components/Story'
import { HomePageGrid } from '../styled-components'
import Profile from '../components/Profile'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Instagram</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomePageGrid>
        <div className={styles.contentContainer}>
          <Stories />
          <Story
            avatar="/profile.png"
            caption="This is a post that I am writing for testing"
            comments={100}
            image="/trerry.png"
            likes={20}
            name="PhantomKnight"
            shares={45}
            timestamp="1 Hour Ago"
          />
        </div>
        <Profile
          avatar="/profile.png"
          name="Phantom Knight"
          username="phantomknight287"
          suggestions={[
            {
              name: 'PhantomKnight',
              avatar: '/profile.png',
              followedBy: 'Followed by Terry Lucas and 2 others',
            },
          ]}
        />
      </HomePageGrid>
    </div>
  )
}

export default Home
